name: core20
version: "20"
summary: Runtime environment based on Ubuntu 20.04
description: |
  The base snap based on the Ubuntu 20.04 release.
confinement: strict
type: base
build-base: core20

parts:
  bootstrap:
    plugin: make
    source: .
    build-packages:
      - shellcheck
      - wget
      - distro-info
    build-envrionment:
      - PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/snap/snapcraft/current/bin/scriptlet-bin"
      - LD_LIBRARY_PATH: ""
    override-build: |
      env
      snapcraftctl build
      make test
    override-prime: |
      env

