#!/bin/sh
set -uxe

# This script requires root
test "$(id -u)" -ne 0 && exit 1

# This script requires an argument (directory name).
test -z "${1:-}" && exit 1
D="$1"

# Expose individual partitions and mount the 3rd partition.
loopNp3=$(kpartx -sav "$D"/image.raw | grep -E -o 'loop[0-9]+p3')
mount /dev/mapper/"$loopNp3" "$D"/p3
