#!/bin/sh
set -uxe

# This script requires root
test "$(id -u)" -ne 0 && exit 1

# This script requires an argument (directory name).
test -z "${1:-}" && exit 1
D="$1"

# Unmount and detach partitions.
umount "$D"/p3
kpartx -sdv "$D"/image.raw
